bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
setw -g mode-keys vi
set -g set-clipboard on

bind C-b send-prefix
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g escape-time 10
set -g focus-events on

set -g base-index 1
set -g status-right ""

setw -g status-style fg=colour255,bg=colour237
setw -g window-status-format '#[fg=colour245] #I #W '
setw -g window-status-current-format '#[bg=colour13,fg=colour255]#{?client_prefix,#[bg=colour198],} #I #W '

set -g copy-command 'pbcopy'

set -g mouse on

bind C-n new-session
bind '%' split-window -h -c '#{pane_current_path}'
bind '"' split-window -v -c '#{pane_current_path}'

set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
