# git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
if-shell 'uname | grep -q Darwin' 'set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'fabioluciano/tmux-tokyo-night'

set -g @theme_variation 'night'
set -g @theme_left_separator ''
set -g @theme_right_separator ''
set -g @theme_plugins 'datetime,weather,playerctl,yay'

setw -g mode-keys vi
set -g set-clipboard on
set -g mouse on
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g renumber-windows on

run '~/.config/tmux/plugins/tpm/tpm'

bind C-b send-prefix
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind C-n new-session
bind '%' split-window -h -c '#{pane_current_path}'
bind '"' split-window -v -c '#{pane_current_path}'
bind '\' split-window -hf -l 25%
bind '_' split-window -vf -l 20%

